import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CheckCircle2, ChevronLeft, CircleUserRound, ClipboardList, LogOut, Menu, Package, Search, Send, X, XCircle } from 'lucide-react'
import { users } from './data'
import { authService, itemService, requestService } from './services'
import type { BorrowRequest, Category, Item, RequestStatus, User } from './types'

type Page='browse'|'items'|'requests'|'incoming'
const categories:('All'|Category)[]=['All','Electronics','Study Tools','Books','Lab Equipment','Stationery','Daily Essentials']
const statusLabel:Record<RequestStatus,string>={pending:'Pending',accepted:'Accepted',rejected:'Rejected',returned:'Returned'}
const date=(s:string)=>new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})

export default function App(){
 const [user,setUser]=useState<User|undefined>(()=>authService.getCurrentUser()),[items,setItems]=useState<Item[]>([]),[requests,setRequests]=useState<BorrowRequest[]>([]),[page,setPage]=useState<Page>('browse'),[detail,setDetail]=useState<Item>(),[menu,setMenu]=useState(false),[loading,setLoading]=useState(false),[notice,setNotice]=useState('')
 const refresh=async()=>{setLoading(true);const [i,r]=await Promise.all([itemService.getItems(),requestService.getRequests()]);setItems(i);setRequests(r);setLoading(false)}
 useEffect(()=>{if(user) refresh()},[user])
 const login=async(u:User)=>{setLoading(true);await authService.login(u);setUser(u);setPage('browse');setLoading(false)}
 const logout=()=>{authService.logout();setUser(undefined);setDetail(undefined);setMenu(false)}
 const mutate=async(fn:()=>Promise<unknown>,success:string)=>{try{await fn();await refresh();setNotice(success);setDetail(undefined);setTimeout(()=>setNotice(''),3200)}catch(e){setNotice(e instanceof Error?e.message:'Something went wrong.')}}
 const resetDemo=()=>{if(window.confirm('Reset all demo data? This will remove all changes made during the current demo.'))mutate(()=>requestService.reset(),'Demo data reset successfully.')}
 if(!user) return <Login loading={loading} login={login}/>
 const nav:{id:Page;label:string;icon:typeof Search}[]=[{id:'browse',label:'Browse Items',icon:Search},{id:'items',label:'My Items',icon:Package},{id:'requests',label:'My Requests',icon:ClipboardList},{id:'incoming',label:'Incoming Requests',icon:Send}]
 return <div className="app"><header><button className="brand" onClick={()=>setPage('browse')}><span className="brand-icon">C</span>CampusConnect</button><nav className={menu?'open':''}>{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setMenu(false)}}><n.icon size={16}/>{n.label}</button>)}</nav><div className="account"><div className="avatar">{user.avatar}</div><span>{user.name}</span><button className="reset" onClick={resetDemo}>Reset demo data</button><button className="logout" onClick={logout}><LogOut size={16}/> <b>Switch account</b></button></div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 {notice&&<div className="toast"><CheckCircle2 size={18}/>{notice}</div>}
 <main>{page==='browse'&&<Browse user={user} items={items} loading={loading} open={setDetail}/>} {page==='items'&&<MyItems user={user} items={items} open={setDetail}/>} {page==='requests'&&<Requests user={user} items={items} requests={requests} outgoing onReturn={id=>mutate(()=>requestService.update(id,'return'),'Item marked as returned — it is available again.')} setPage={setPage}/>} {page==='incoming'&&<Requests user={user} items={items} requests={requests} onAccept={id=>mutate(()=>requestService.update(id,'accept'),'Request accepted. The item is now unavailable.')} onReject={id=>mutate(()=>requestService.update(id,'reject'),'Request rejected. The item remains available.')} />}</main>
 {detail&&<Detail item={detail} user={user} owner={users.find(u=>u.id===detail.ownerId)!} close={()=>setDetail(undefined)} request={()=>mutate(()=>requestService.create(detail.id,user.id),'Borrow request sent successfully!')}/>}</div>
}

function Login({login,loading}:{login:(u:User)=>void;loading:boolean}){return <div className="login"><section className="login-intro"><div className="campus-mark">C</div><p className="eyebrow">CAMPUS ITEM SHARING</p><h1>Borrow what you need.<br/><em>Share what you have.</em></h1><p>CampusConnect helps students borrow and share useful items within their college community.</p><div className="benefits"><span>✓ Simple demo flow</span><span>✓ Built for campus life</span><span>✓ No sign-up required</span></div></section><section className="login-panel"><div><p className="eyebrow">DEMO VERSION</p><h2>Welcome to CampusConnect</h2><p className="muted">Choose an account to explore both borrower and lender flows.</p></div><div className="login-cards">{users.map(u=><article className="user-card" key={u.id}><div className="avatar large">{u.avatar}</div><div><h3>{u.name}</h3><p>{u.department} · {u.year}</p><small>{u.collegeId}</small></div><button disabled={loading} onClick={()=>login(u)}>Continue <span>→</span></button></article>)}</div><p className="demo-note">Select either account — you can switch anytime from the navigation.</p></section></div>}

function Browse({user,items,loading,open}:{user:User;items:Item[];loading:boolean;open:(i:Item)=>void}){const [search,setSearch]=useState(''),[cat,setCat]=useState<'All'|Category>('All'),[available,setAvailable]=useState(false);const list=useMemo(()=>items.filter(i=>i.ownerId!==user.id&&i.name.toLowerCase().includes(search.toLowerCase())&&(cat==='All'||i.category===cat)&&(!available||i.available)),[items,user,search,cat,available]);return <><section className="hero"><p className="eyebrow">CAMPUS MARKETPLACE</p><h1>Good afternoon, {user.name.split(' ')[0]} <span>👋</span></h1><p>Find something you need on campus.</p></section><section className="filters"><label className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search calculators, books, chargers..."/></label><select value={cat} onChange={e=>setCat(e.target.value as 'All'|Category)}>{categories.map(c=><option key={c}>{c==='All'?'All Categories':c}</option>)}</select><label className="toggle"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/><span/>Available only</label></section><section className="section-head"><div><h2>Items shared nearby</h2><p>Available from other students in your campus community</p></div><span>{list.length} item{list.length!==1?'s':''}</span></section>{loading?<Loading text="Loading items..."/>:list.length?<div className="grid">{list.map(i=><ItemCard key={i.id} item={i} owner={users.find(u=>u.id===i.ownerId)!} open={open}/>)}</div>:<Empty title="No items found" text="No items match your search or filters." action={()=>{setSearch('');setCat('All');setAvailable(false)}}/>}</>}
function ItemCard({item,owner,open}:{item:Item;owner:User;open:(i:Item)=>void}){return <article className="item-card" onClick={()=>open(item)}><div className="item-image">{item.image}<span className={`badge ${item.available?'available':'unavailable'}`}>{item.available?'Available':'Unavailable'}</span></div><div className="item-content"><div className="card-top"><span className="category">{item.category}</span><span className="condition">{item.condition}</span></div><h3>{item.name}</h3><p>{item.description}</p><div className="owner"><div className="avatar small">{owner.avatar}</div><span>Shared by <b>{owner.name.split(' ')[0]}</b></span></div><button disabled={!item.available} onClick={e=>{e.stopPropagation();open(item)}}>{item.available?'Borrow item':'Currently unavailable'}</button></div></article>}
function MyItems({user,items,open}:{user:User;items:Item[];open:(i:Item)=>void}){const own=items.filter(i=>i.ownerId===user.id);return <><section className="hero compact"><p className="eyebrow">YOUR SHARED ITEMS</p><h1>My items</h1><p>Items you’ve made available to the CampusConnect community.</p></section><div className="grid">{own.map(i=><ItemCard key={i.id} item={i} owner={user} open={open}/>)}</div></>}
function Requests({user,items,requests,outgoing,onReturn,onAccept,onReject,setPage}:{user:User;items:Item[];requests:BorrowRequest[];outgoing?:boolean;onReturn?:(id:string)=>void;onAccept?:(id:string)=>void;onReject?:(id:string)=>void;setPage?:(p:Page)=>void}){const list=requests.filter(r=>outgoing?r.borrowerId===user.id:r.ownerId===user.id);const title=outgoing?'My requests':'Incoming requests';return <><section className="hero compact"><p className="eyebrow">{outgoing?'BORROWING ACTIVITY':'LENDER DASHBOARD'}</p><h1>{title}</h1><p>{outgoing?'Track items you have asked to borrow.':'Review requests for items you have shared.'}</p></section>{list.length?<div className="request-list">{list.map(r=>{const item=items.find(i=>i.id===r.itemId)!;const person=users.find(u=>u.id===(outgoing?r.ownerId:r.borrowerId))!;return <article className="request-card" key={r.id}><div className="request-image">{item.image}</div><div className="request-copy"><div className="request-title"><div><h3>{item.name}</h3><p>{outgoing?'Shared by':'Requested by'} <b>{person.name}</b> · {date(r.createdAt)}</p></div><span className={`status ${r.status}`}>{statusLabel[r.status]}</span></div><p className="request-message">{r.status==='pending'?'Waiting for the owner to respond.':r.status==='accepted'?outgoing?'Your request has been accepted.':'This item is currently with the borrower.':r.status==='rejected'?'Your borrow request was rejected.':'Item successfully returned.'}</p></div><div className="request-actions">{outgoing&&r.status==='accepted'&&<button onClick={()=>onReturn?.(r.id)}>Mark as returned</button>}{!outgoing&&r.status==='pending'&&<><button onClick={()=>onAccept?.(r.id)}>Accept</button><button className="outline-danger" onClick={()=>onReject?.(r.id)}>Reject</button></>}</div></article>})}</div>:<Empty title={outgoing?'No outgoing requests':'No incoming requests'} text={outgoing?"You haven't requested any items yet.":"You don't have any borrow requests right now."} action={outgoing?()=>setPage?.('browse'):undefined} actionText="Browse items"/>}</>}
function Detail({item,user,owner,close,request}:{item:Item;user:User;owner:User;close:()=>void;request:()=>void}){const own=item.ownerId===user.id;return <div className="modal-backdrop" onClick={close}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="detail-image">{item.image}</div><div className="detail-body"><div className="card-top"><span className="category">{item.category}</span><span className={`badge ${item.available?'available':'unavailable'}`}>{item.available?'Available now':'Currently unavailable'}</span></div><h2>{item.name}</h2><p className="detail-description">{item.description}</p><div className="detail-info"><span>Condition <b>{item.condition}</b></span><span>Category <b>{item.category}</b></span></div><div className="shared"><div className="avatar large">{owner.avatar}</div><div><small>SHARED BY</small><h3>{owner.name}</h3><p>{owner.department} · {owner.year}</p></div></div>{own?<p className="own-note">This is one of your shared items.</p>:<button className="primary large-button" disabled={!item.available} onClick={request}>{item.available?'Request to borrow':'Currently unavailable'}</button>}</div></section></div>}
function Empty({title,text,action,actionText='Clear filters'}:{title:string;text:string;action?:()=>void;actionText?:string}){return <div className="empty"><Package size={34}/><h3>{title}</h3><p>{text}</p>{action&&<button onClick={action}>{actionText}</button>}</div>}
function Loading({text}:{text:string}){return <div className="loading"><span/> {text}</div>}
